# Generated by Django 2.2 on 2019-04-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('key', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('encryptedId', models.CharField(max_length=63, unique=True)),
                ('puuid', models.CharField(max_length=78)),
                ('accountId', models.CharField(max_length=56)),
                ('level', models.IntegerField(default=0)),
                ('iconId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionMastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('tokenEarned', models.IntegerField(default=0)),
                ('lastPlayTime', models.BigIntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Champion')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Summoner', to_field='encryptedId')),
            ],
            options={
                'unique_together': {('summoner', 'champion')},
            },
        ),
    ]
